export const ErrorCodes = {
  // General errors
  INTERNAL_ERROR: 'ERR_INTERNAL',
  VALIDATION_ERROR: 'ERR_VALIDATION',
  UNAUTHORIZED: 'ERR_UNAUTHORIZED',
  FORBIDDEN: 'ERR_FORBIDDEN',
  NOT_FOUND: 'ERR_NOT_FOUND',
  RATE_LIMITED: 'ERR_RATE_LIMITED',

  // Transaction errors
  TRANSACTION_FAILED: 'ERR_TRANSACTION_FAILED',
  TRANSACTION_NOT_FOUND: 'ERR_TRANSACTION_NOT_FOUND',
  TRANSACTION_ALREADY_PROCESSED: 'ERR_TRANSACTION_ALREADY_PROCESSED',
  INSUFFICIENT_FUNDS: 'ERR_INSUFFICIENT_FUNDS',
  INVALID_AMOUNT: 'ERR_INVALID_AMOUNT',

  // Transfer errors
  TRANSFER_FAILED: 'ERR_TRANSFER_FAILED',
  TRANSFER_TIMEOUT: 'ERR_TRANSFER_TIMEOUT',
  INVALID_ACCOUNT: 'ERR_INVALID_ACCOUNT',
  ACCOUNT_NOT_FOUND: 'ERR_ACCOUNT_NOT_FOUND',

  // UnionBank API errors
  UNIONBANK_API_ERROR: 'ERR_UNIONBANK_API',
  UNIONBANK_AUTH_FAILED: 'ERR_UNIONBANK_AUTH',
  UNIONBANK_TIMEOUT: 'ERR_UNIONBANK_TIMEOUT',

  // Idempotency errors
  DUPLICATE_REQUEST: 'ERR_DUPLICATE_REQUEST',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
