export enum DepositStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum DepositType {
  INSTAPAY = 'INSTAPAY',
  PESONET = 'PESONET',
  BANK_TRANSFER = 'BANK_TRANSFER',
  CASH_IN = 'CASH_IN',
}

export interface Deposit {
  // Document ID (auto-generated by Firestore)
  id: string;

  // User information
  userId: string;
  firstName: string;
  lastName: string;
  email: string;

  // Transaction details
  depositId: string;
  amount: number;
  phpAmount: number;
  currency: string;

  // Status and type
  status: DepositStatus;
  type: DepositType;

  // Timestamps
  createdAt: Date;
  time: string;

  // Optional fields
  externalReferenceId?: string;
  statusMessage?: string;
  failureReason?: string;
  completedAt?: Date;
  metadata?: Record<string, unknown>;
}

export interface CreateDepositData {
  userId: string;
  firstName: string;
  lastName: string;
  email: string;
  depositId: string;
  amount: number;
  phpAmount: number;
  currency: string;
  type: DepositType;
  metadata?: Record<string, unknown>;
}

export interface UpdateDepositData {
  status?: DepositStatus;
  externalReferenceId?: string;
  statusMessage?: string;
  failureReason?: string;
  completedAt?: Date;
  metadata?: Record<string, unknown>;
}
